luskan/Dockerfile, storage-inventory-dm/README.md
=> update storage-inventory-dm README with implementation/behaviour details

minoc/src/intTest/java/org/opencadc/minoc/BasicOpsTest.java, minoc/src/intTest/java/org/opencadc/minoc/IncorrectPutMetadataTest.java, minoc/src/intTest/java/org/opencadc/minoc/MinocTest.java, minoc/src/intTest/java/org/opencadc/minoc/ReplaceArtifactTest.java
so assert failures get out properly
=> changed test code to catch unexpected Exception rather than Throwable

cadc-inventory/build.gradle, cadc-inventory/src/main/java/org/opencadc/inventory/StorageSite.java, cadc-inventory/src/test/java/org/opencadc/inventory/EntityTest.java, minoc/src/main/java/org/opencadc/minoc/ArtifactAction.java
made StorageSite fields mutable so a site could update resourceID and /or name
=> implemented StorageSite init in minoc

cadc-inventory/src/main/java/org/opencadc/inventory/InventoryUtil.java, cadc-inventory/src/main/java/org/opencadc/inventory/StoredArtifactComparator.java, cadc-storage-adapter/src/main/java/org/opencadc/inventory/storage/StorageAdapter.java
improved javadoc for StorageAdapter (iterator and list)
=> added StoredArtifactComparator

cadc-storage-adapter-fs/README.md, cadc-storage-adapter-fs/build.gradle, cadc-storage-adapter-fs/src/main/java/org/opencadc/inventory/storage/fs/FileSystemIterator.java, cadc-storage-adapter-fs/src/main/java/org/opencadc/inventory/storage/fs/FileSystemStorageAdapter.java, cadc-storage-adapter-fs/src/test/java/org/opencadc/inventory/storage/fs/FileSystemStorageAdapterTest.java
Fixes opencadc/storage-inventory#57
=> s2697, ta13024, issue #57: add transaction and content directories for put

luskan/src/main/java/org/opencadc/luskan/ws/StorageTapService.java, minoc/src/main/java/org/opencadc/minoc/ServiceAvailability.java, raven/src/main/java/org/opencadc/raven/ServiceAvailability.java
Fixes opencadc/storage-inventory#61
Includes raven & luskan availability fixes as well.
=> s2697, ta 13049, issue #61: availability should check cadcproxy cert

cadc-inventory-db/build.gradle, cadc-inventory-db/src/intTest/java/org/opencadc/inventory/db/ArtifactDAOTest.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/AbstractDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/SQLGenerator.java
=> bug fix for forceUpdate timestamp and set fetch direction and limit for artifact iterator

minoc/build.gradle, minoc/src/main/java/org/opencadc/minoc/ArtifactAction.java, minoc/src/main/java/org/opencadc/minoc/InitDatabaseAction.java, minoc/src/main/java/org/opencadc/minoc/ServiceAvailability.java, minoc/src/main/webapp/WEB-INF/web.xml
fixed check permission logic and error messages
removed extraneous Subject.doAs in getUserGroups()
added temporary disable group permission checks to support development; may make it an option for testing
=> fixed compile and runtime dependencies for GMS

tantar/src/main/java/org/opencadc/tantar/BucketValidator.java, tantar/src/main/java/org/opencadc/tantar/Main.java
- Replaced Properties loading with PropertiesReader.
- Replaced Properties with MultiValuedProperties in Main and BucketValidator.
=> Fixed error logging.

cadc-inventory-db/build.gradle, cadc-inventory-db/src/intTest/java/org/opencadc/inventory/db/HarvestStateDAOTest.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/HarvestState.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/HarvestStateDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/SQLGenerator.java, cadc-inventory-db/src/main/resources/inventory.Artifact.sql, cadc-inventory-db/src/main/resources/inventory.HarvestState.sql, cadc-inventory-db/src/main/resources/inventory.upgrade-0.8.sql
increased size of storage bucket column
=> inventory-db-0.8: added HarvestState tracker

fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, minoc/README.md, minoc/build.gradle, minoc/src/intTest/java/org/opencadc/minoc/IncorrectPutMetadataTest.java, minoc/src/intTest/java/org/opencadc/minoc/MinocTest.java, minoc/src/main/java/org/opencadc/minoc/ArtifactAction.java, minoc/src/main/java/org/opencadc/minoc/InitDatabaseAction.java, minoc/src/main/java/org/opencadc/minoc/PutAction.java, raven/README.md, raven/src/main/java/org/opencadc/raven/PostAction.java, raven/src/main/webapp/WEB-INF/web.xml
via external grant provider service 
with developer-only bypass for local intTest
=> minoc and raven permission checking

critwall/build.gradle, critwall/src/main/java/org/opencadc/critwall/FileSync.java, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java, critwall/src/main/java/org/opencadc/critwall/Main.java
Also ensure that exceptions are passed up.
=> Fixes #148

critwall/build.gradle, critwall/src/intTest/java/org/opencadc/critwall/FileSyncJobTest.java, critwall/src/intTest/java/org/opencadc/critwall/FileSyncTest.java, critwall/src/main/java/org/opencadc/critwall/FileSync.java, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java, critwall/src/main/java/org/opencadc/critwall/Main.java, critwall/src/main/java/org/opencadc/critwall/ThreadPool.java
with hack for existing raven bug
=> critwall: enable run forever and query to refill job queue

cadc-inventory/build.gradle, cadc-inventory/src/main/java/org/opencadc/inventory/InventoryUtil.java, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java, fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, minoc/README.md, minoc/build.gradle, minoc/src/main/java/org/opencadc/minoc/ArtifactAction.java, minoc/src/main/java/org/opencadc/minoc/MinocInitAction.java, raven/README.md, raven/build.gradle, raven/src/intTest/java/org/opencadc/raven/NegotiationTest.java, raven/src/main/java/org/opencadc/raven/PostAction.java
fenwick bug fix
critwall log improvements
=> minoc & raven: made public/private keys for pre-auth negotiated URLs configurable

minoc/src/intTest/README.md, minoc/src/intTest/java/org/opencadc/minoc/ReplaceArtifactTest.java, minoc/src/main/java/org/opencadc/minoc/PutAction.java
apparently we now need a comment in order to enable the create button. That sucks github.
=> minoc: bug fix to allow overwriting an artifact with no local storage location

luskan/src/main/java/org/opencadc/luskan/LuskanConfig.java, luskan/src/main/java/org/opencadc/luskan/LuskanInitAction.java, luskan/src/main/java/org/opencadc/luskan/ws/StorageTapService.java
Restored property file check to the startup init, and added it to the availability check.
=> S2768 luskan query correctness

cadc-inventory-db/build.gradle, cadc-inventory-db/src/intTest/java/org/opencadc/inventory/db/HarvestStateDAOTest.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/HarvestState.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/SQLGenerator.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/version/InitDatabase.java, cadc-inventory-db/src/main/resources/inventory.HarvestState.sql, cadc-inventory-db/src/main/resources/inventory.upgrade-0.10.sql, cadc-inventory/src/test/java/org/opencadc/inventory/EntityTest.java, critwall/src/intTest/java/org/opencadc/critwall/FileSyncJobTest.java, critwall/src/main/java/org/opencadc/critwall/FileSync.java, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java, fenwick/build.gradle, fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, minoc/PutTransaction.md
PutTransaction straw-man proposal
critwall: more conservative FileSyncJob artifact updating
fenwick: improve logging and fix merge logic bug when trackSiteLocations==true
=> initial put transaction doc

fenwick/src/main/java/org/opencadc/fenwick/IncludeArtifacts.java, fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, fenwick/src/main/java/org/opencadc/fenwick/Main.java
* Added pre-check for `artifact-filter.sql` include file.  Bug from a fix for #166.
* Moved Subject creation to before each sync job.
Looking for acceptance for this part while carrying on with moving the DataSource allocation.
=> WIP: Fixes #201

luskan/src/main/java/org/opencadc/luskan/TempStorageManager.java, luskan/src/main/java/org/opencadc/luskan/ws/QueryJobManager.java
Tried to create a unit test for this, but too many preconditions. I did hack together a test to confirm it is deleting as expected after the time interval has elapsed.
=> CADC-1309 luskan async query results cleanup issue #56 aka CADC-8532

fenwick/src/intTest/java/org/opencadc/fenwick/InventoryHarvesterTest.java, fenwick/src/main/java/org/opencadc/fenwick/ArtifactSync.java, fenwick/src/main/java/org/opencadc/fenwick/DeletedArtifactEventSync.java, fenwick/src/main/java/org/opencadc/fenwick/DeletedStorageLocationEventSync.java, fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, fenwick/src/test/java/org/opencadc/fenwick/ArtifactSyncTest.java
Create an upper bound for all queries to ensure new artifacts are not out of sync with deleted Artifact events.
=> Fixes #160

fenwick/src/intTest/java/org/opencadc/fenwick/InventoryHarvesterTest.java, fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java
for put race conditions and missed DeletedArtifactEvent(s)
=> resolve Artifact.uri collision logic CADC-8578

fenwick/src/intTest/java/org/opencadc/fenwick/InventoryHarvesterTest.java
=> CADC-1309 fenwick int test improvements

baldur/Dockerfile, baldur/README.md, baldur/VERSION, critwall/Dockerfile, critwall/README.md, critwall/VERSION, critwall/build.gradle, fenwick/Dockerfile, fenwick/README.md, fenwick/VERSION, fenwick/build.gradle, luskan/Dockerfile, luskan/README.md, luskan/VERSION, luskan/build.gradle, minoc/Dockerfile, minoc/README.md, minoc/VERSION, raven/README.md, raven/VERSION, tantar/Dockerfile, tantar/README.md, tantar/VERSION, tantar/build.gradle
simplified application docker files by removing version attr from build.gradle
=> add VERSION file with semantic and build version tags; CADC-8612

cadc-storage-adapter-swift/build.gradle, cadc-storage-adapter-swift/src/intTest/java/org/opencadc/inventory/storage/swift/MultiBucketSwiftStorageAdapterTest.java, cadc-storage-adapter-swift/src/intTest/java/org/opencadc/inventory/storage/swift/SwiftByteRangeTest.java, cadc-storage-adapter-swift/src/main/java/org/opencadc/inventory/storage/swift/SwiftStorageAdapter.java, cadc-storage-adapter-swift/src/test/java/org/opencadc/inventory/storage/swift/SwiftStorageAdapterTest.java, cadc-storage-adapter/build.gradle, cadc-storage-adapter/src/main/java/org/opencadc/inventory/storage/InvalidConfigException.java, cadc-storage-adapter/src/main/java/org/opencadc/inventory/storage/StorageAdapter.java
cadc-storage-adapter-swift: improved exceptions from ctor and added config parsing tests
=> cadc-storage-adapter: added InvalidConfigException, documented exceptiosn that constructors could throw

ringhold/src/main/java/org/opencadc/ringhold/InventoryValidator.java, ringhold/src/main/java/org/opencadc/ringhold/Main.java
add info logging for processed artifact, fixed NullPointerException for missing config file
=> Cadc-8572 ringhold

minoc/src/intTest/java/org/opencadc/minoc/ReplaceArtifactTest.java
=> Fix integration test to wait and allow dates to differ.

raven/src/intTest/java/org/opencadc/raven/FilesTest.java, raven/src/intTest/java/org/opencadc/raven/NegotiationTest.java, raven/src/intTest/java/org/opencadc/raven/RavenTest.java, raven/src/intTest/java/org/opencadc/raven/VosiAvailabilityTest.java, raven/src/intTest/java/org/opencadc/raven/VosiCapabilitiesTest.java, raven/src/main/java/org/opencadc/raven/ArtifactAction.java, raven/src/main/java/org/opencadc/raven/FilesAction.java, raven/src/main/java/org/opencadc/raven/GetFilesAction.java, raven/src/main/java/org/opencadc/raven/HeadFilesAction.java, raven/src/main/java/org/opencadc/raven/PostAction.java, raven/src/main/java/org/opencadc/raven/ProtocolsGenerator.java, raven/src/main/java/org/opencadc/raven/RavenInitAction.java, raven/src/main/java/org/opencadc/raven/ServiceAvailability.java, raven/src/main/webapp/WEB-INF/web.xml, raven/src/main/webapp/capabilities.xml, raven/src/main/webapp/service.yaml, raven/src/test/java/org/opencadc/raven/FilesActionTest.java
=> Add "files" end point to the maven service

raven/src/intTest/java/org/opencadc/raven/FilesTest.java, raven/src/main/java/org/opencadc/raven/FilesAction.java, raven/src/main/java/org/opencadc/raven/GetFilesAction.java, raven/src/test/java/org/opencadc/raven/FilesActionTest.java
add TODO to pass through optional params to storage
=> disable prototype default scheme support

cadc-inventory-util/build.gradle, cadc-inventory/build.gradle, cadc-inventory/src/main/java/org/opencadc/inventory/Artifact.java, cadc-inventory/src/main/java/org/opencadc/inventory/InventoryUtil.java, cadc-storage-adapter-swift/build.gradle, cadc-storage-adapter-swift/src/intTest/java/org/opencadc/inventory/storage/swift/MultiBucketSwiftStorageAdapterTest.java, cadc-storage-adapter-swift/src/intTest/java/org/opencadc/inventory/storage/swift/SingleBucketSwiftStorageAdapterTest.java, cadc-storage-adapter-swift/src/intTest/java/org/opencadc/inventory/storage/swift/SwiftByteRangeTest.java, cadc-storage-adapter-swift/src/main/java/org/opencadc/inventory/storage/swift/BucketNameGenerator.java, cadc-storage-adapter-swift/src/main/java/org/opencadc/inventory/storage/swift/SwiftStorageAdapter.java, cadc-storage-adapter-swift/src/test/java/org/opencadc/inventory/storage/swift/BucketNameGeneratorTest.java, cadc-storage-adapter-swift/src/test/java/org/opencadc/inventory/storage/swift/SwiftStorageAdapterTest.java
create buckets  on init
store immutable config as bucket attrs in storage
fix intTest init to override some config from user config file
=> support init of buckets in SwiftStorageAdapter

minoc/src/intTest/java/org/opencadc/minoc/BasicOpsTest.java, minoc/src/main/java/org/opencadc/minoc/GetAction.java, minoc/src/main/java/org/opencadc/minoc/PutAction.java
added incorrect content-length tests to assist detecting front-end that intercedes and closes stream on put
=> fix Get and Put to log number of bytes

cadc-inventory-db/build.gradle, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/AbstractDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/ArtifactDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/HarvestStateDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/StorageSiteDAO.java, raven/src/main/java/org/opencadc/raven/HeadFilesAction.java
raven: throw artifact not found in HEAD request
=> cadc-inventory-db: add basic error handling to unwrap Spring JDBC exceptions

ratik/README.md, ratik/src/intTest/java/org/opencadc/ratik/InventoryValidatorTest.java, ratik/src/main/java/org/opencadc/ratik/ArtifactValidator.java, ratik/src/main/java/org/opencadc/ratik/InventoryValidator.java, ratik/src/main/java/org/opencadc/ratik/Main.java
add info log messages when queries return iterators
add summary log message at end of validation
=> ratik: make config style consistent with fenwick

luskan/src/intTest/java/org/opencadc/luskan/AuthQueryTest.java, luskan/src/main/java/org/opencadc/luskan/TapSchemaDAOImpl.java
fix anon test to expect 401 NotAuthenticatedException
=> add date to function whitelist

cadc-inventory-util/build.gradle, cadc-inventory-util/src/main/java/org/opencadc/inventory/query/ArtifactRowMapper.java, cadc-storage-adapter-ad/src/main/java/org/opencadc/inventory/storage/ad/AdStorageAdapter.java, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java, ratik/build.gradle, ratik/src/intTest/java/org/opencadc/ratik/InventoryValidatorTest.java, ratik/src/main/java/org/opencadc/ratik/ArtifactValidator.java, ratik/src/main/java/org/opencadc/ratik/InventoryValidator.java
it will confirm multiple copies in global before deleting
=> CADC-10140 CADC-10135 if ratik finds a nonpolicy Artifact in local storage

critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java
avoid sleep for retry when there are no urls left
=> critwall: drop url from list after auth failure

minoc/Dockerfile, minoc/build.gradle, minoc/src/intTest/java/org/opencadc/minoc/FitsOperationsTest.java, minoc/src/intTest/java/org/opencadc/minoc/FitsTest.java, minoc/src/main/java/org/opencadc/minoc/GetAction.java, minoc/src/main/java/org/opencadc/minoc/operations/CutoutFileNameFormat.java, minoc/src/main/webapp/WEB-INF/web.xml, minoc/src/test/java/org/opencadc/minoc/operations/CutoutFileNameFormatTest.java
Incorporate new NoOverlapException
Add path for WCS sky cutouts
=> Complete sky cutouts in GET request

cadc-inventory-db/build.gradle, cadc-inventory-db/src/intTest/java/org/opencadc/inventory/db/ArtifactDAOTest.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/AbstractDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/ArtifactDAO.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/SQLGenerator.java, fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, minoc/src/main/webapp/service.yaml, ratik/src/intTest/java/org/opencadc/ratik/InventoryEnvironment.java, ratik/src/intTest/java/org/opencadc/ratik/InventoryValidatorTest.java, ratik/src/main/java/org/opencadc/ratik/ArtifactValidator.java, ratik/src/main/java/org/opencadc/ratik/InventoryValidator.java, raven/src/main/webapp/service.yaml, storage-inventory-dm/README.md
when adding SiteLocation in global
=> cadc-inventory-db: add Artifact change event (update lastModified)

ratik/src/intTest/java/org/opencadc/ratik/InventoryValidatorTest.java, ratik/src/main/java/org/opencadc/ratik/ArtifactValidator.java, ratik/src/main/java/org/opencadc/ratik/InventoryValidator.java, storage-inventory-dm/README.md
handle discrepancy where local artifact is missing siteLocation of remote
=> ratik: change local set to be all artifacts in db

ratik/src/main/java/org/opencadc/ratik/ArtifactValidator.java, ratik/src/main/java/org/opencadc/ratik/InventoryValidator.java
add single retry for get remote entity queries in ArtifactValidator
=> fix artifact counts to reset when retrying bucket

fenwick/src/main/java/org/opencadc/fenwick/InventoryHarvester.java, luskan/src/intTest/resources/SyncResultTest-date.properties, opencadc.gradle, ratik/src/intTest/java/org/opencadc/ratik/InventoryValidatorTest.java, ratik/src/main/java/org/opencadc/ratik/ArtifactValidator.java, ratik/src/main/java/org/opencadc/ratik/InventoryValidator.java, storage-inventory-dm/README.md
document race condition in metadata-validate scenario
ratik: implement race condition detection and delay action, logging tweaks
fenwick: logging improvements and summary logging
=> fenwick and ratik improvements

critwall/VERSION, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java
"downloadAuth" has not been tested yet. Will test it when the black network is available.
=> Cadc 11056 Add more log outputs to FileSyncJob.END

raven/build.gradle, tantar/src/main/java/org/opencadc/tantar/BucketValidator.java, tantar/src/main/java/org/opencadc/tantar/ValidateEventListener.java, tantar/src/main/java/org/opencadc/tantar/policy/StorageIsAlwaysRight.java, tantar/src/test/java/org/opencadc/tantar/TestEventListener.java
StorageIsAlwaysRight policy:  handle unmatchedStorageLocation
=> tantar: allow policy to get artifact by uri

cadc-storage-adapter-ad/build.gradle, cadc-storage-adapter-ad/src/main/java/org/opencadc/inventory/storage/ad/AdStorageAdapter.java, cadc-storage-adapter-fs/build.gradle, cadc-storage-adapter-fs/src/intTest/java/org/opencadc/inventory/storage/fs/OpaqueStorageAdapterPreserveTest.java, cadc-storage-adapter-fs/src/main/java/org/opencadc/inventory/storage/fs/FileSystemStorageAdapter.java, cadc-storage-adapter-fs/src/main/java/org/opencadc/inventory/storage/fs/OpaqueFileSystemStorageAdapter.java, cadc-storage-adapter-swift/build.gradle, cadc-storage-adapter-swift/src/intTest/java/org/opencadc/inventory/storage/swift/SwiftPreserveNamespaceTest.java, cadc-storage-adapter-swift/src/main/java/org/opencadc/inventory/storage/swift/SwiftStorageAdapter.java, cadc-storage-adapter-test/build.gradle, cadc-storage-adapter-test/src/main/java/org/opencadc/inventory/storage/test/StorageAdapterBasicTest.java, cadc-storage-adapter/build.gradle, cadc-storage-adapter/src/main/java/org/opencadc/inventory/storage/StorageAdapter.java
add optional recovery test scenarios to test suite
=> add StorageAdapter.recover() method to API and implementations

cadc-storage-adapter-swift/build.gradle, cadc-storage-adapter-swift/src/main/java/org/opencadc/inventory/storage/swift/SwiftStorageAdapter.java, critwall/src/main/java/org/opencadc/critwall/FileSyncJob.java
critwall: log unexpected terminal FileSyncJob exceptions with full stack trace
=> cadc-storage-adapter-swift: catch all joss CommandException

fenwick/README.md, fenwick/VERSION, fenwick/src/main/java/org/opencadc/fenwick/AbstractSync.java, fenwick/src/main/java/org/opencadc/fenwick/ArtifactSync.java, fenwick/src/main/java/org/opencadc/fenwick/DeletedArtifactEventSync.java, fenwick/src/main/java/org/opencadc/fenwick/DeletedStorageLocationEventSync.java, fenwick/src/main/java/org/opencadc/fenwick/StorageLocationEventSync.java
added harvest state init to StorageLocationEventSync
=> fenwick: fix bug where maintenace code ran inside transaction

cadc-inventory-db/src/intTest/java/org/opencadc/vospace/db/NodeDAOTest.java, cadc-inventory-db/src/main/java/org/opencadc/inventory/db/SQLGenerator.java, vault/build.gradle, vault/src/intTest/java/org/opencadc/vault/NodesTest.java, vault/src/main/java/org/opencadc/vault/NodePersistenceImpl.java, vault/src/main/java/org/opencadc/vault/VaultInitAction.java, vault/src/main/webapp/capabilities.xml
with the fix in cadc-access-control-identity, viewing the root node now works
=> vault updates

minoc/README.md, minoc/build.gradle, minoc/src/intTest/java/org/opencadc/minoc/FitsOperationsTest.java, minoc/src/intTest/java/org/opencadc/minoc/FitsTest.java, minoc/src/intTest/java/org/opencadc/minoc/MetaTest.java, minoc/src/intTest/resources/sample-mef.txt, minoc/src/main/java/org/opencadc/minoc/GetAction.java, minoc/src/main/java/org/opencadc/minoc/operations/ProxyRandomAccessFits.java
Depends on https://github.com/opencadc/dal/pull/95.
=> Test updates and adapt to nom-tam-fits 1.18.0.

cadc-inventory-db/src/main/java/org/opencadc/vospace/db/NodeDAO.java, vault/build.gradle, vault/src/main/java/org/opencadc/vault/NodePersistenceImpl.java
plus NodeDAO(boolean origin) ctor for migrate
=> DataNode date prop fix

minoc/src/intTest/java/org/opencadc/minoc/FitsOperationsTest.java, minoc/src/main/java/org/opencadc/minoc/GetAction.java
this makes sure that vault cutouts have the real fits file name and not the opaque vault storage id
=> minoc: use filenameOverride feature in cutout logic

.github/workflows/gradle.yml, vault/README.md, vault/VERSION, vault/build.gradle, vault/src/main/java/org/opencadc/vault/NodePersistenceImpl.java, vault/src/main/java/org/opencadc/vault/ServiceAvailability.java, vault/src/main/java/org/opencadc/vault/VaultInitAction.java
add config option: enableDataNodeSizeWorker
=> vault: dependency update for iterator leak

vault/VERSION, vault/src/main/java/org/opencadc/vault/NodePersistenceImpl.java
allows NodePersistenceImpl to recover if AAI is down at startup
=> vault: lazy init of root node

minoc/VERSION, minoc/build.gradle
Depends on the `opencadc/dal.git` PR https://github.com/opencadc/dal/pull/104.
=> Reflect new FITS fix.

baldur/VERSION, cadc-storage-adapter-fs/build.gradle, cadc-storage-adapter-fs/src/main/java/org/opencadc/inventory/storage/fs/OpaqueFileSystemStorageAdapter.java, critwall/VERSION, fenwick/VERSION, luskan/VERSION, minoc/VERSION, ratik/VERSION, raven/VERSION, ringhold/VERSION, tantar/VERSION, tantar/build.gradle, vault/VERSION
if stored files are missing required xattrs
=> cadc-storage-adapter-fs: storage iterator warn and skip

cadc-storage-adapter-eos/src/intTest/java/org/opencadc/inventory/storage/eos/EosStorageAdapterTest.java, minoc/VERSION, tantar/VERSION
cadc-storage-adapter-eos: add failed iteration test
=> minoc and tantar: image version update
